### PR TITLE
Redis filter

### PR DESCRIPTION
**Pull request by keenondrums**
Tests added
unexpected behavior of computeNextRunTime fixed

### CODE REVIEW

**Comment by lykmapipo** [comment]
@keenondrums 

May you please create an issue for `unexpected behavior of computeNextRunTime` it will help us to know what was the problem.

Thanks.

**Comment by lykmapipo** [comment]
@keenondrums 

I have been working on this too. I will merge it soon.

I appreciate.

**Comment by lykmapipo** [comment]
@keenondrums 

I think you getting that  because all job expiry key are save using the following pattern
`kue prefix:scheduler:uuid` and you ar publishing `q:message` and expect a worker to perform the job.

But well am on it hope i will resolve with your pull request and merge.

**Comment by keenondrums** [comment]
>I think you getting that because all job expiry key are using kue prefix:scheduler:uuid pattern and you are publishing q:message and expect a worker to perform the job.

I thinnk it's the issue. In fact it's nearly impossible to get an incorrect message with a "q" prefix. But in case if we did it's much better to fall gracefully with a schedule error, not with some unhandled exception.

**Comment by lykmapipo** [comment]
@keenondrums 

> I thinnk it's the issue. In fact it's nearly impossible to get an incorrect message with a "q" prefix. But in case if we did it's much better to fall gracefully with a schedule error, not with some unhandled exception.

I have add `scheduler unknown job expiry key` event which emit unknown key than on `kue` instance.
I see that is better than propagation thrown error all over.

**Pull request merged**
