### PR TITLE
Update expiry key validator regex

### PR DESCRIPTION
**Pull request by fennecbutt**
* Updated expiry key validator regex
* Tidied a few related things up

### CODE REVIEW

**Comment by lykmapipo** [comment]
@fennecbutt Thanks for the PR.

I saw you are using `string template`. Can we use normal string concatenation until we are sure that most of user have already upgrade to latest node version.

**Comment by lykmapipo** [comment]
@fennecbutt CI is failing cause of `string template`.

**Comment by fennecbutt** [comment]
Yeah, I'll change from templated strings back to regular old strings in a sec. I've just gotten into the habit of using 'em. 😄

**Comment by lykmapipo** [comment]
@fennecbutt Thanks.

**Comment by lykmapipo** [comment]
@fennecbutt Thanks. I will work on release

**Pull request merged**
