### PR TITLE
Kue update

### PR DESCRIPTION
**Pull request by KeKs0r**
Here my PR to update Kue to 10.3

I have tried the new Kue version on staging, but not yet on Production. Just want to open it to put it on the roadmap and start evaluating it.

### CODE REVIEW

**Comment by lykmapipo** [comment]
@KeKs0r 

I will work on it this weekend. Hope you have checked [0.9 -> 0.10](https://github.com/Automattic/kue/wiki/Upgrading-to-0.10.x) upgrade.

Thanks for PR.

**Comment by KeKs0r** [comment]
@lykmapipo I did take care of this for my environment. But I think if we tackle this we should make it a new kue-scheduler major version and add the same release notes.

**Comment by lykmapipo** [comment]
@KeKs0r 

Sure. That was actually the purpose of my question.
We will have to update major version and add release notes.

:+1:

**Comment by KeKs0r** [comment]
Hey @lykmapipo 
can we move forward with this? The kue 9->10 upgrade only states that you should start with a clean redis instance. So the same applies for upgrading kue-scheduler.

**Comment by elyas-bhy** [comment]
+1, looking for to this PR.

**Comment by lykmapipo** [comment]
@KeKs0r & @elyas-bhy 

I will work on this. It will be out after fix the merge

**Comment by KeKs0r** [comment]
I also did the update for the devdependencies in order to see the actual test output. Seems that we still have some issues with it.

**Comment by KeKs0r** [comment]
@lykmapipo : ping

**Comment by KeKs0r** [comment]
@lykmapipo : I guess this can be closed, since you updated kue to 10.5

**Pull request closed without merging**
