### PR TITLE
Multi process scheduler

### PR DESCRIPTION
**Pull request by gmcnaught**
Firstly: did a simple clean up of tests so they pass 90% of the time. 
 -- There seems to be a situation with mocha where the connection to redis can be closed and an event fire, which causes tests to fail that I did not resolve.

Secondly: added redlock around the 'every' and _onJobExpiry to force only a single worker that gets the key expiration method to schedule the next run of the job. This may need an improvement / modification for clustered redis scenarios, as redlock needs to know all of the redis servers it needs to get quorum from on a lock.

### CODE REVIEW

**Comment by gmcnaught** [comment]
This should resolve #24 and #21

**Comment by fruch** [comment]
@gmcnaught so now we could use the same schudle from multiple processes, and it will be activated only one ?
i.e. I want to have mulitple hosts running the schuduler code (for redundencey/backup) is there a suggested way of achiving it ?

**Comment by Roam-Cooper** [comment]
Yes, it would be nice to have some confirmation of this behaviour.

**Comment by fruch** [comment]
ו'll try to update once I tested it. (It's crucial for my implementation)

**Comment by gmcnaught** [comment]
Yes, in my use case I specifically tested this across multiple servers
connected to the same resis instance.

**Comment by fruch** [comment]
@gmcnaught and ? kue-unique is working as expected ? Can you share some code snippet how you did you tested ?

**Comment by fruch** [comment]
I've test it and it's not working as I expected:
I have this setup (see below)
and once I activate all three, I see my task happening twice every 10sec

How can I lock it so it won't happend twice ? (and still keep cron1 cron2 for backup of one anther)

```javascript
//cron1.js
    var job = Queue
                .createJob('upm-scanning', {to: 'any'})
                .attempts(1)
                .backoff({delay: 10000, type: 'fixed'})
                .priority('normal');

    //schedule it to run every 10 seconds
    Queue.every('10 seconds', job);

```

```javascript
//cron2.js
    var job = Queue
                .createJob('upm-scanning', {to: 'any'})
                .attempts(1)
                .backoff({delay: 10000, type: 'fixed'})
                .priority('normal');

    //schedule it to run every 10 seconds
    Queue.every('10 seconds', job);
```

```javascript
//worker.js
    queue.process('upm-scanning', upmScanningTask);
```

**Comment by gmcnaught** [comment]
Your example code is creating two jobs, so two jobs are being run. You can
either follow a producer-consumer model and only run queue.createJob in a
single worker, or add a unique constraint so that any of your workers
attempting to create the same job will instead use the already created job.

**Comment by fruch** [comment]
unique did that trick, thanks.
(for some reason when I first tried it, it seems like it's not working, and triggering the job only once)

**Pull request merged**
